# Generated by Django 5.2.4 on 2025-09-05 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_register_phone_alter_register_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customcakerequest',
            name='reference_cake',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.cake'),
        ),
        migrations.AddField(
            model_name='order',
            name='custom_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.customcakerequest'),
        ),
        migrations.AlterField(
            model_name='cakereview',
            name='cake',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='home.cake'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cake',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.cake'),
        ),
    ]
